version: "3.9"
services:
  python:
    image: nnurgulklc/python-project:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_DB: ${POSTGRES_DB} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_HOST_ADD: ${POSTGRES_HOST_ADD}
      POSTGRES_PORT: ${POSTGRES_PORT} 
    ports: 
      - "8888:8888"
    depends_on:
      - postgresql
    secrets:
      - python_env
  
  postgresql: 
    image: postgres:14.6-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD_FILE: run/secrets/postgresPass
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    secrets:
      - postgresPass
      - python_env

secrets:
  python_env:
    file: .env
  postgresPass:
    file: postgresPass.txt


